/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Triangle */

#ifndef _Included_Triangle
#define _Included_Triangle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Triangle
 * Method:    form
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Triangle_form
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
